# Generated by Django 2.2.3 on 2019-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(default='', upload_to='students/images'),
        ),
    ]
