# Generated by Django 2.2.3 on 2019-09-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_branch_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='batch',
            field=models.CharField(default='', max_length=30),
        ),
    ]
