# Generated by Django 2.2.3 on 2019-09-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20190912_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
