# Generated by Django 2.2.3 on 2019-09-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_memories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='image',
            field=models.ImageField(upload_to='students/memories'),
        ),
    ]
