# Generated by Django 2.2.3 on 2019-10-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_pictures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Memories',
        ),
    ]
