# Generated by Django 2.2.3 on 2019-10-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_delete_memories'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='picno',
            field=models.IntegerField(null=True),
        ),
    ]
